frite:
    resource: "@FriteBundle/Resources/config/routing.yml"
    prefix:   /

baskel:
    resource: "@FriteBundle/Resources/config/routing.yml"
    prefix:   /Frite

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"