fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
panier:
    resource: "@PanierBundle/Resources/config/routing.yml"
    prefix:   /Panier

baskel:
    resource: "@BaskelBundle/Resources/config/routing.yml"
    prefix:   /Baskel

app:
    resource: '@AppBundle/Controller/'
    type: annotation


