panier:
    resource: "@PanierBundle/Resources/config/routing.yml"
    prefix:   /Panier

baskel:
    resource: "@BaskelBundle/Resources/config/routing.yml"
    prefix:   /Baskel

app:
    resource: '@AppBundle/Controller/'
    type: annotation
