<?php

namespace forumBundle\Repository;

/**
 * otificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class otificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
