<?php

namespace BaskelBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function FindAllProducts()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT p.nomP, p.prixP, p.image, p.couleurP FROM BaskelBundle:Produits p'
        )->setMaxResults(8);

        return $query->getResult();
    }
}
