<?php

namespace LivraisonBundle\Repository;

/**
 * LivreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
    public function ModifierSolde($id,$solde){

        $query = $this->getEntityManager()
            ->createQuery(" UPDATE LivraisonBundle:Livreur c SET c.solde =  c.solde+:solde 
 where c.id =:id ")
            ->setParameter('solde',$solde)
            ->setParameter('id', $id)
        ;
        return $query->getResult();
    }
}
