<?php

namespace Produits\ProduitsBundle\Repository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository
{
    public function AddToWishlist()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT p.refP ,p.nomP, p.prixP, p.quantiteP ,u.id 
            FROM Produits\ProduitsBundle:Produits , FOSUSERBundle\USER u where p.refP= :refP and u.id= :id_client'
        );

        return $query->getResult();
    }

    public function FindWishlists($id)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT p.couleurP 
            FROM ProduitsBundle:Produits p where p.refP= :refP and u.id= :id_client'
        );

        return $query->getResult();
    }

    public function FindTheWishlist($id_client,$refP)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT w
            FROM ProduitsBundle:Wishlist w where w.refP= :refP and w.idClient= :id_client'
        )->setParameter('id_client',$id_client)
        ->setParameter('refP',$refP);

        return $query->getResult();
    }


}
