panier_homepage:
    path:     /
    defaults: { _controller: PanierBundle:Default:afficherProduits }
afficherProduit:
    path:     /afficherProduit
    defaults: { _controller: PanierBundle:Default:afficherProduits }
ajouterAuPanier:
    path:     /ajouterAuPanier
    defaults: { _controller: PanierBundle:Default:ajouterAuPanier }
MyCart:
    path:     /MyCart
    defaults: { _controller: PanierBundle:Default:MyCart }
ModifierQte:
    path:     /ModifierQte
    defaults: { _controller: PanierBundle:Default:ModifierQte }
SupprimerItem:
    path:     /SupprimerItem
    defaults: { _controller: PanierBundle:Default:SupprimerItem }
Valider:
    path:     /Valider
    defaults: { _controller: PanierBundle:Default:Valider }

AfficherCommande:
    path:     /AfficherCommande/
    defaults: { _controller: PanierBundle:Default:AfficherCommande }

ModifierEtatCommande:
    path:     /ModifierEtatCommande/{id}/{etat}
    defaults: { _controller: PanierBundle:Default:ModifierEtatCommande }

AfficherDetailsCommande:
    path:     /AfficherDetailsCommande/{id}
    defaults: { _controller: PanierBundle:Default:AfficherDetailsCommande }


SupprimerCommande:
    path:     /SupprimerCommande/{id}
    defaults: { _controller: PanierBundle:Default:SupprimerCommande }
afficherCommandeDunUser:
    path:     /afficherCommandeDunUser
    defaults: { _controller: PanierBundle:Default:afficherCommandeDunUser }
CountPanier:
    path:     /CountPanier
    defaults: { _controller: PanierBundle:Default:CountPanier }

AllCommandeJson:
    path:     /AllCommandeJson
    defaults: { _controller: PanierBundle:Default:AllCommandeJson }

AllDetailsCommandeJson:
    path:     /AllDetailsCommandeJson/{id}
    defaults: { _controller: PanierBundle:Default:AllDetailsCommandeJson }

ReadAllCommandeJson:
    path:     /ReadAllCommandeJson
    defaults: { _controller: PanierBundle:Default:ReadAllCommandeJson }

AllProductsJson:
    path:     /AllProductsJson
    defaults: { _controller: PanierBundle:Default:AllProductsJson }

LouayPanierCommandeJson:
    path:     /LouayPanierCommandeJson/{size}/{PrixTotal}/{idClient}
    defaults: { _controller: PanierBundle:Default:LouayPanierCommandeJson }

NouayDetailsCommandeJson:
    path:     /NouayDetailsCommandeJson/{Commande}/{getRefP}/{getNomP}/{getPrixP)
    defaults: { _controller: PanierBundle:Default:NouayDetailsCommandeJson }

DetailsJson:
    path:     /DetailsJson/{id}/{ref}/{nom}/{prix}
    defaults: { _controller: PanierBundle:Default:DetailsJson }
SendMailApresValiderJson:
    path:     /SendMailApresValiderJson
    defaults: { _controller: PanierBundle:Default:SendMailApresValiderJson }


ReadAllUserJson:
    path:     /ReadAllUser
    defaults: { _controller: PanierBundle:Default:ReadAllUsersJson }
login_api:
    path:     /login_api/{username}/{password}
    defaults: { _controller: PanierBundle:Default:Login }


ReadAllLivraisonJson:
    path:     /ReadAllLivraisonJson
    defaults: { _controller: PanierBundle:Default:ReadAllLivraisonJson }
AddLivraisonJson:
    path:     /AddLivraisonJson/{Commande}/{idLivreur}
    defaults: { _controller: PanierBundle:Default:AddLivraisonJson }
ReadLivreurJson:
    path:     /ReadLivreurJson
    defaults: { _controller: PanierBundle:Default:ReadLivreurJson }
ConfirmerJson:
    path:     /ConfirmerJson/{id}
    defaults: { _controller: PanierBundle:Default:ConfirmerJson }
getlivcomJson:
    path:     /getlivcomJson/{commande}
    defaults: { _controller: PanierBundle:Default:getlivcomJson }
EtatCommandeJson:
    path:     /EtatCommandeJson
    defaults: { _controller: PanierBundle:Default:EtatCommandeJson }
coderecup:
    path:     /coderecup/{id}
    defaults: { _controller: PanierBundle:Default:coderecup }
ReadVehiculeJson:
    path:     /ReadVehiculeJson
    defaults: { _controller: PanierBundle:Default:ReadVehiculeJson }
AjoutVehiculeJson:
    path:     /AjoutVehiculeJson/{matricule}/{marque}/{type}
    defaults: { _controller: PanierBundle:Default:AjoutVehiculeJson }
ModifierVehiculeJson:
    path:     /ModifierVehiculeJson/{id}/{matricule}/{marque}/{type}
    defaults: { _controller: PanierBundle:Default:ModifierVehiculeJson }
SupprimerVehiculeJSON:
    path:     /SupprimerVehiculeJSON/{id}
    defaults: { _controller: PanierBundle:Default:SupprimerVehiculeJSON }


ReadAllEventJson:
    path:     /ReadAllEventJson
    defaults: { _controller: PanierBundle:Default:ReadAllEventJson }

ReadAllPartenairetJson:
    path:     /ReadAllPartenaireJson
    defaults: { _controller: PanierBundle:Default:ReadAllPartenaireJson }

SupprimerReservationJSON:
    path:     /SupprimerReservationJSON/{id}
    defaults: { _controller: PanierBundle:Default:SupprimerReservationJSON }

ReadAllReservationtJson:
    path:     /ReadAllReservationJson/{idClient}
    defaults: { _controller: PanierBundle:Default:ReadAllReservationJson }
ReserverJson:
    path:     /ReserverJson/{idEvent}/{idClient}
    defaults: { _controller: PanierBundle:Default:ReserverJson }