baskel_homepage:
    path:     /
    defaults: { _controller: BaskelBundle:Default:index }


afficherProduits:
    path:     /afficherProduits
    defaults: { _controller: BaskelBundle:Produits:afficherProduits }


ajouterCategorie:
    path:     /ajouterCategorie
    defaults: { _controller: BaskelBundle:Produits:ajouterCategorie }


afficherCategories:
  path:     /afficherCategories
  defaults: { _controller: BaskelBundle:Produits:afficherCategories }

supprimerCategorie:
  path:     /SupprimerCategorie/{ref_c}
  defaults: { _controller: BaskelBundle:Produits:SupprimerCategorie }



ajouterProduit:
  path:     /ajouterProduit
  defaults: { _controller: BaskelBundle:Produits:ajouterProduit }




afficherProduitsBack:
  path:     /afficherProduitsBack
  defaults: { _controller: BaskelBundle:Produits:afficherProduitsBack }


supprimerProduit:
  path:     /supprimerProduit/{ref_p}
  defaults: { _controller: BaskelBundle:Produits:supprimerProduit }


modifierCategorie:
  path:     /modifierCategorie/{ref_c}
  defaults: { _controller: BaskelBundle:Produits:modifierCategorie }


modifierProduit:
  path:     /modifierProduit/{ref_p}
  defaults: { _controller: BaskelBundle:Produits:modifierProduit }


modalContent:
  path:     /modalContent
  defaults: { _controller: BaskelBundle:Produits:modalContent }