baskel_homepage:
    path:     /
    defaults: { _controller: BaskelBundle:Default:index }
admin_homepage:
    path:     /admin
    defaults: { _controller: BaskelBundle:Default:indexAdmin }
pdf:
    path:     /pdf
    defaults: { _controller: BaskelBundle:Default:pdf }
ImgFaq:
    path:     /ImgFaq
    defaults: { _controller: BaskelBundle:Default:ImgFaq }


