baskel_homepage:
    path:     /
    defaults: { _controller: BaskelBundle:Default:index }
admin_homepage:
    path:     /admin
    defaults: { _controller: BaskelBundle:Default:indexAdmin }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"