baskel_homepage:
    path:     /
    defaults: { _controller: BaskelBundle:Default:index }
admin_homepage:
    path:     /admin
    defaults: { _controller: BaskelBundle:Default:indexAdmin }
rdv:
    path:     /rdv
    defaults: { _controller: BaskelBundle:Default:AjouterRDV }
reclamation:
    path:     /reclamation
    defaults: { _controller: BaskelBundle:Default:AjouterReclamation }
AfficherReclamations:
    path:     /recBack
    defaults: { _controller: BaskelBundle:Default:AfficherReclamations }
AfficherRDV:
    path:     /rdvBack
    defaults: { _controller: BaskelBundle:Default:AfficherRDV }
AfficherTechniciens:
    path:     /tecBack
    defaults: { _controller: BaskelBundle:Default:AfficherTechniciens }
SupprimerRDV:
    path:     /SupprimerRDVBack/{id}
    defaults: { _controller: BaskelBundle:Default:SupprimerRDV }
SupprimerReclamation:
    path:     /SupprimerRecBack/{id}
    defaults: { _controller: BaskelBundle:Default:SupprimerReclamation }
SupprimerTechnicien:
    path:     /SupprimerTecBack/{id}
    defaults: { _controller: BaskelBundle:Default:SupprimerTechnicien }
AjouterTechnicien:
    path:     /AjouterTecBack
    defaults: { _controller: BaskelBundle:Default:AjouterTechnicien }
DisplayReclamation:
    path:     /ListRec
    defaults: { _controller: BaskelBundle:Default:DisplayReclamation }
DisplayRdv:
    path:     /ListRdv
    defaults: { _controller: BaskelBundle:Default:DisplayRdv }
DeleteReclamation:
    path:     /RecDelete/{id}
    defaults: { _controller: BaskelBundle:Default:DeleteReclamation }
DeleteRDV:
    path:     /RdvDelete/{id}
    defaults: { _controller: BaskelBundle:Default:DeleteRDV }
ModifierReclamation:
    path:     /ModifRec/{id}
    defaults: { _controller: BaskelBundle:Default:ModifierReclamation }
ModifierRDV:
    path:     /ModifRDV/{id}
    defaults: { _controller: BaskelBundle:Default:ModifierRDV }
ModifierTechnicien:
    path:     /ModifTech/{id}
    defaults: { _controller: BaskelBundle:Default:ModifierTechnicien }