baskel_homepage:
    path:     /
    defaults: { _controller: BaskelBundle:Default:index }
admin_homepage:
    path:     /admin
    defaults: { _controller: BaskelBundle:Default:indexAdmin }
livreur_homepage:
    path:     /livreur
    defaults: { _controller: BaskelBundle:Default:indexLivreur }
affvehicule:
    path:     /affvehicule
    defaults: { _controller: BaskelBundle:Vehicule:afficheVehicule }
ajoutvehicule:
    path:     /ajoutvehicule
    defaults: { _controller: BaskelBundle:Vehicule:ajout }
suppvehicule:
    path:     /suppvehicule/{id}
    defaults: { _controller: BaskelBundle:Vehicule:supprimer }
modifiervehicule:
    path:     /modifiervehicule/{id}
    defaults: { _controller: BaskelBundle:Vehicule:modifier }
consliv:
    path:     /consliv
    defaults: { _controller: BaskelBundle:Livreur:afficheLivreur }
modifetat:
    path:     /modifetat/{id}
    defaults: { _controller: BaskelBundle:Livreur:modifEtat }
modifsolde:
    path:     /modifsolde/{id}
    defaults: { _controller: BaskelBundle:Livreur:modifSolde }

sendMail:
    path:     /Mail
    defaults: { _controller: AppBundle:Mail:sendMail }
pdf:
    path:     /pdf/{id}
    defaults: { _controller: BaskelBundle\Controller\LivreurController::pdfAction }