baskel_homepage:
    path:     /
    defaults: { _controller: BaskelBundle:Default:index }
admin_homepage:
    path:     /admin
    defaults: { _controller: BaskelBundle:Default:indexAdmin }
pdf:
    path:     /pdf
    defaults: { _controller: BaskelBundle:Default:pdf }
ImgFaq:
    path:     /ImgFaq
    defaults: { _controller: BaskelBundle:Default:ImgFaq }
crankset:
    path:     /crankset
    defaults: { _controller: BaskelBundle:Default:crankset}
wheel:
    path:     /wheel
    defaults: { _controller: BaskelBundle:Default:wheel}
handlebars:
    path:     /handlebars
    defaults: { _controller: BaskelBundle:Default:handlebars}
saddle:
    path:     /saddle
    defaults: { _controller: BaskelBundle:Default:saddle}

Game:
    path:     /Game
    defaults: { _controller: BaskelBundle:Default:Game}

