<?php

namespace EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTopEvent() {
        $query = $this->getEntityManager()->createQuery("SELECT ev FROM EventBundle:Event ev WHERE ev.nbParticipants = (SELECT MAX(e.nbParticipants) FROM EventBundle:Event e)");

        $s= $query->getArrayResult();
        dump($s);
        return $s;
    }

    public function getWorstEvent() {
        $query = $this->getEntityManager()->createQuery("SELECT ev FROM EventBundle:Event ev WHERE ev.nbParticipants = (SELECT MIN(e.nbParticipants) FROM EventBundle:Event e)");
        $s= $query->getArrayResult();
        dump($s);
        return $s;
    }

    public function ClosestEvent(){

        $query = $this->getEntityManager()->createQuery("SELECT ev FROM EventBundle:Event ev WHERE ev.date = (SELECT MIN(e.date) FROM EventBundle:Event e)");
        $s= $query->getArrayResult();
        dump($s);
        return $s;

    }


}
