<?php

namespace EventBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    public function TestReservation($ide,$idu) {
        $query = $this->getEntityManager()->createQuery("SELECT res FROM EventBundle:Reservation res WHERE res.id_event=:ide AND res.id_user=:idu")
            ->setParameter('ide',$ide)
            ->setParameter('idu',$idu);

        $s= $query->getResult();

        return $s;
    }


    public function NBReservation() {
        $query = $this->getEntityManager()->createQuery("SELECT COUNT(res) FROM EventBundle:Reservation res WHERE res.etat='confirme'");

        $s= $query->getSingleScalarResult();
        dump($s);
        return $s;
    }

    public function NBReservationAnnule() {
        $query = $this->getEntityManager()->createQuery("SELECT COUNT(res) FROM EventBundle:Reservation res WHERE res.etat='annule'");

        $s= $query->getSingleScalarResult();
        dump($s);
        return $s;
    }

    public function NBReservationfrit() {
        $query = $this->getEntityManager()->createQuery("SELECT COUNT(res) FROM EventBundle:Reservation res WHERE res.etat='reserve'");

        $s= $query->getSingleScalarResult();
        dump($s);
        return $s;
    }
}
