<?php

namespace PanierBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{

    public function ModifierEtat($id,$etat){

        $query = $this->getEntityManager()
            ->createQuery(" UPDATE PanierBundle:Commande c 
SET c.etat = 1
 where c.id =:id ")
            ->setParameter('id', $id)
         ;
        return $query->getResult();
    }

    public  function Supprimer($id){

    $query = $this->getEntityManager()
        ->createQuery(" DELETE FROM PanierBundle:DetailsCommande c 
          where c.idCommande =:id ")
        ->setParameter('id', $id)
    ;
    return $query->getResult();
}

}
