<?php

namespace PanierBundle\Repository;

/**
 * DetailsCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailsCommandeRepository extends \Doctrine\ORM\EntityRepository
{


}
